### PR TITLE
Manually encapsulate Shady DOM from upstream styles

### PR DESCRIPTION
**Pull request by seaneking**
Resets all styles on all elements to initial values, then re-applies default browser stylesheet, before doing regular Simpla (Shadow DOM) reset.

May result in minor perf hit (none obvious during testing), but this should be worth it until all/most evergreen browsers adopt Shadow DOM. If there's a way to apply only to Shady DOM then no downside at all.

### CODE REVIEW

**Comment by bedeoverend** [comment]
LGTM

**Comment by seaneking** [comment]
Failing tests are old news. Merging.

**Comment by seaneking** [comment]
merged manually

**Comment by seaneking** [comment]
Problem: when using extended elements (eg: `button is="sm-ui-button"`)  _inside_ other Simpla components, the reset for the base element overrides the `:host` styling of the custom component. Not sure how to fix.

**Pull request merged**
